name: mushroom
description: Maritime Route Management Mobile Application
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^12.1.3
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # HTTP
  http: ^1.1.0
  dio: ^5.4.0
  
  # UI
  cupertino_icons: ^1.0.6
  
  # Map
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  
  # Utils
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true